### ISSUE TITLE
Higher Resolution Icon

### ISSUE THREAD

**Issue by vayan** [magefree/Launcher#11]
I'm doing some packaging for MacOS (My fork: https://github.com/vayan/MageLauncher/releases) 

I was wondering if you guys had a higher resolution of this icon : https://github.com/magefree/Launcher/blob/master/src/main/resources/icon-mage.png

**Comment by JayDi85** [comment]
64x64 is the max... You can find icon or png file here (icon-mage...)
https://github.com/magefree/mage/tree/master/Mage.Client/src/main/resources

But [you can find free to use icons](https://www.iconfinder.com/search/?q=magic+hat&price=free) like that 256x256:
https://www.iconfinder.com/icons/61479/hat_magic_wizard_icon#size=256

Or that 128x128:
https://www.iconfinder.com/icons/34846/halloween_hat_witch_hat_icon

**Comment by vayan** [comment]
Ok! I'll do that, thanks.
