### ISSUE TITLE
test mode is not being able to be set through the launcher or its properties?

### ISSUE THREAD

**Issue by Susucre** [magefree/Launcher#24]
I am used to start the test mode with an IDE, starting server directly from there. Command line should work fine too with `-testMode=true` argument.

There seems to be the possibility to do it through the launcher, by adding `xmage.server.testmode=true` to `installed.property`, but that does not seem to work. Am I missing something?

Setting is read there:
https://github.com/magefree/Launcher/blob/56d3dde5d2a1c5278c9aa85a99443f2bfb8e011b/src/main/java/com/xmage/launcher/Config.java#L82
And used there:
https://github.com/magefree/Launcher/blob/56d3dde5d2a1c5278c9aa85a99443f2bfb8e011b/src/main/java/com/xmage/launcher/Utilities.java#L105

**Comment by JayDi85** [comment]
Current release/beta launcher is outdated and don't have additional settings like test mode, settings reset, etc. You can build own launcher from the sources and replace the current jar with it.

Or just wait next release. I added property settings support in https://github.com/magefree/mage/commit/c515ff383ce17ab26b669c24d68befa1703ce76c, so you can add it by launcher -> server params like `-Dxmage.testMode=true`. Also updated [instructions in the wiki](https://github.com/magefree/mage/wiki/Development-Testing-Tools) about running options.
