### ISSUE TITLE
New release, please.

### ISSUE THREAD

**Issue by allentiak** [magefree/Launcher#27]
Hi, @JayDi85,

The last stable version is 10 years old, and the code has evolved since.

Would you be so kind as to do a new release, please?

**Comment by JayDi85** [comment]
New launcher will come with java 17 migration. It’s not a critical feature. Most important for current state — server’s stability (server crashes fixes) and long list of un-implemented cards.

**Comment by xenohedron** [comment]
It may not be a "critical feature" but what is the downside to releasing the updated launcher? There are substantial improvements from #14 that are unreleased. As far as I can tell we aren't close to java 17 migration being ready.

**Comment by JayDi85** [comment]
Launcher has auto-update feature and I don't test it at all. Maybe it doesn't work at all. Possible use cases:
- from old to new (with unacceptable de-config, with today-config);
- from new to new (with unacceptable de-config, with today-config).

**Comment by xenohedron** [comment]
I've built an updated version on my fork https://github.com/xenohedron/xmage-java-launcher/releases/tag/v0.4.1

Adjusted default config settings to enable use of any java version per https://github.com/magefree/mage/issues/12768 (so system java should work)
* Adjusted default memory to 2GB client, 1GB server
* Replaced backgrounds to align with new Carbon Fiber theme
* Updated links to default branches

@allentiak maybe you would like to try it and see what you think?

**Comment by allentiak** [comment]
Hi, @xenohedron,
Thank you for your hard work!
I tried your build, and it seems to work fine.

That being said, I'm afraid your effort may be moot.
Please, allow me to elaborate.

To sum it up, unless @JayDi85 decides to:
a) become omniscient and do everything a big project like XMage demands, or
b) become humble (and wise) enough to accept there is no way one single person cant take care of managing the whole project by himself, and therefore ditch his command-and-control approach and finally delegate responsibilities onto others and accept their input (like in this case, yours)

time will continue to pass, and people will still be using an installer which is over 10 years old.

Or, as I did, they will move on and switch to other alternatives, more open to help from third parties like Forge, https://github.com/Card-Forge/forge.

**Comment by JayDi85** [comment]
@allentiak if you want to help and make it faster then you can test miss use cases, see my comments about potential problems:
https://github.com/magefree/Launcher/issues/27#issuecomment-2054155503

Launcher is critical part of the software and it can be broken for many players on irresponsible release without testing. There were problems even with the https.
